### ISSUE TITLE
backend code analyse

### ISSUE THREAD

**Issue by geunho** [GeunhoKim/grafana#2]
#### TODOs
- [x] pull upstream/master 4.0.1
- [x] install go plugin on intellij
- [x] find entrypoint to alert settings
- [ ] find entrypoint to write db

#### Remarks
- forward proxy 셋업
- 테스트 코드 작성
